---
apiVersion: v1
kind: Service
metadata:
  name: watson-reviews
  labels:
    app: watson-reviews
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  type: LoadBalancer
  selector:
    app: watson-reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watson-reviews-deployment
  labels:
    app: watson-reviews
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: watson-reviews
    spec:
      containers:
        - image: horeaporutiu/watson-review-analyzer:2.1
          imagePullPolicy: Always
          name: watson-reviews
          env:
            - name: CLOUDANT_URL
              value: 'http://admin:password@couchdb:5984'
          volumeMounts:
            - name: config-file
              mountPath: "/app/config.json"
              subPath: "config.json"
              readOnly: true
          ports:
            - containerPort: 4000
      volumes:
        - name: config-file
          configMap:
            name: watson-discovery-config